package com.zula.database.core;

import java.time.LocalDateTime;

/**
 * Base POJO for entities used with JDBI. Previously used as a JPA @MappedSuperclass.
 * For JDBI we keep simple fields and setters/getters and let JDBI mappers bind columns to properties.
 */
public abstract class BaseEntity {

    // keep id as a simple Long (generated by DB); JDBI will read/write it explicitly
    private Long id;

    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
}
